region = "us-east-1"

vpc_name = "prod_ITI_vpc"
vpc_cidr = "10.0.0.0/16"

public_subnet1_cidr = "10.0.1.0/24"
public_subnet2_cidr = "10.0.2.0/24"
private_subnet1_cidr = "10.0.3.0/24"
private_subnet2_cidr = "10.0.4.0/24"

public_subnet1_name = "prod_public_subnet1"
public_subnet2_name = "prod_public_subnet2"
private_subnet1_name = "prod_private_subnet1"
private_subnet2_name = "prod_private_subnet2"